export enum Departament {
  ADMINISTRATION = "ADMINISTRATION",
  MARKETING = "MARKETING",
  SALES = "SALES",
  IT = "IT",
  FINANCE = "FINANCE",
  HR = "HR",
  CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
  MANAGEMENT = "MANAGEMENT",
  TECHNOLOGY = "TECHNOLOGY",
}